[package]
name = "zklink_contract_serde"
version = "0.1.0"


[dependencies]
alexandria_math.workspace = true
starknet.workspace = true
openzeppelin.workspace = true

zklink = { path = "../zklink_starknet_contracts" }

#[scripts]
#test.workspace = true
#snforge.workspace = true
