[package]
name = "zklink_test_model"
version = "0.1.0"


[dependencies]
alexandria_math.workspace = true
starknet.workspace = true
openzeppelin.workspace = true

zklink = { path = "../zklink_starknet_contracts" }

#[scripts]
#test.workspace = true

#[tool]
#snforge.workspace = true

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true

# Enable CASM codegen.
casm = true

# Emit Python-powered hints in order to run compiled CASM class with legacy Cairo VM.
casm-add-pythonic-hints = true

# Enable allowed libfuncs validation.
allowed-libfuncs = true
allowed-libfuncs-list.name = "all"

# Raise errors instead of warnings if disallowed libfuncs are found.
#allowed-libfuncs-deny = false
# Reference to the libfuncs allowlist used for validation.
# - Use `allowed-libfuncs-list.name` to use built-in named allowlist.
# - Use `allowed-libfuncs-list.path` to read an allowlist from file.
#allowed-libfuncs-list = {} # Cairo compiler defined

# Emit Starknet artifacts for contracts defined in dependencies.
#build-external-contracts = []
